- _locales/de/messages.json
- _locales/en/messages.json
- _locales/es/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/ja/messages.json
- _locales/ko/messages.json
- _locales/nl/messages.json
- _locales/pt_BR/messages.json
- _locales/ru/messages.json
- _locales/tr/messages.json
- _locales/zh_CN/messages.json
- _locales/zh_TW/messages.json
- content_scripts/cip.js
- content_scripts/cipDefine.js
- content_scripts/cipEvents.js
- content_scripts/cipFields.js
- content_scripts/cipPassword.js
- content_scripts/mpDialog.js
- mooltipass-content.js
- ui/custom-credentials-selection/custom-credentials-selection.js
- Added a description section at the begining of the following scripts;
1) content_scripts\cip.js
2) content_scripts\cipDefine.js
3) content_scripts\cipEvents.js
4) content_scripts\cipFields.js
5) content_scripts\cipPassword.js
6) content_scripts\mpDialog.js
7) mooltipass-content.js
- Removed the following legacy functions from content scripts:
1) cip.js->doSubmit()
2) cipDefine.js->isFieldSelected()
3) cipFields.js->setFormUniqueId()
4) cipPassword.js->onRequestPassword()
5) cipPassword.js->callbackGeneratedPassword()
6) cipPassword.js->callbackPasswordCopied()
7) mpDialog.js->onHideDialog()
- Implemented missing localization logic to:
1) UI/custom-credentials-selection.html
> Added descriptions to the newly created content scripts.

- content_scripts/cip.js
- content_scripts/cipDefine.js
- content_scripts/cipEvents.js
- content_scripts/cipFields.js
- content_scripts/cipPassword.js
- content_scripts/mpDialog.js
Added function documentation to the following:
- content_scripts\cip.js
- content_scripts\cipEvents.js
- content_scripts\cipFields.js
- content_scripts\cipDefine.js
- content_scripts\cipPassword.js
- content_scripts\mpDialog.js
> Documented functions

- vendor/mooltipass/mcCombinations.js
- Updated mcCombinations.js to detect Log-In button on GMAIL.COM
> Added GMAIL compatibility

- updateCleanVersion.sh
- Updated updateCleanVersion.sh to build an Opera extension package [.nex]
> Build OPERA extension package

- content_scripts/cipPassword.js
- Updated setIconPosition() to handle generic styling for all types of fields
>  Apply generic styling to credential icons

- vendor/mooltipass/mcCombinations.js
- Search bar was being detected as UserName input field
> Fixed compatibility issue with leclercdrive.fr

- mooltipass-content.js
- Content scripts were not being loaded into local pages (chrome-extensions://...)
> Fixed HttpAuth compatibility

- documentation/README.md
- vendor/mooltipass/mcCombinations.js
- Created new combination to support testing 2 step logins
- Updated documentation to reflect current state
> Support 2-step-login test page

- vendor/mooltipass/mcCombinations.js
- Added "next" to the list of text's to identify submit buttons
> Added "next" to the list of accepted buttons

- vendor/mooltipass/mcCombinations.js
- Extend Form action extracter to handle "javascript" actions.
> Update extracting form action url's

- vendor/mooltipass/mcCombinations.js
- Handle validation checkers which blank password fields on submitting the form.
> Handle FORM validation checks

- vendor/mooltipass/mcCombinations.js
- Added 'mohela.com' to the list.
> Extended DISABLE_AUTOSUBMIT_DOMAINS list

- vendor/mooltipass/mcCombinations.js
- Mark detected submit buttons with unique id.
- Prevent re-detecting the same button twice.
> Assign unique ID's to detected submit buttons

- background/event.js
- content_scripts/cipEvents.js
- mooltipass-content.js
- Updated ContentScript to be Safari compilant
> Fixed Safari compatibility issue [ci-ext]

- vendor/mooltipass/mcCombinations.js
- Added special combination for this domain
> Fixed "https://protonmail.uservoice.com/password"

- background/event.js
- background/init.js
- content_scripts/cipEvents.js
-fixed high CPU load on sites with multiple subframes
-New fields monitored by mutation observer
> CPU usage optimisation

- content_scripts/cipEvents.js
-monitors for style changes
-2 delays before scanning nodes - 500 and 1500ms
> Mutation observer fixes

- popups/js/popup_status.js
Open App/App missing updated if app found when popup open
> App status in popup

- popups/js/popup_status.js
Disabled localisation for Safari in popup
> Safari fix

- background/page.js
- content_scripts/cip.js
- content_scripts/cipEvents.js
Clear tab cache after 30 seconds.
Bug fixes
> Issue 52 and bug fixes

- mooltipass-content.js
Special rule to fix login iframe on connect.garmin.com
> Fix for connect.garmin.com

- vendor/mooltipass/mcCombinations.js
Fixed issue on
https://www.wonderpens.ca/AccountSettings.asp?modwhat=change_a and
similar forms
> Updated loginform004

- background/event.js
- background/init.js
- vendor/mooltipass/mcCombinations.js
Fixes for high CPU usage with NoScript add-ons installed
> CPU load fix

- popups/js/popup_status.js
- vendor/mooltipass/website.js
Fixed report issue in FF
small fixes in popup in FF
> Firefox bug fixes

- _locales/de/messages.json
- _locales/en/messages.json
- _locales/es/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/ja/messages.json
- _locales/ko/messages.json
- _locales/nl/messages.json
- _locales/pt_BR/messages.json
- _locales/ru/messages.json
- _locales/tr/messages.json
- _locales/zh_CN/messages.json
- _locales/zh_TW/messages.json
- vendor/mooltipass/device.js
Stop asking the credentials after 3 unsuccessful attempts
> case of 3 unsuccessful login

- vendor/mooltipass/device.js
- vendor/mooltipass/mcCombinations.js
fix for issue 108
change in detectSubmitButton
added comments in device.js
> fix for issue 108

- mooltipass-content.css
fixes for CSS (!important modificator)
> fixes for CSS

- content_scripts/cip.js
- vendor/mooltipass/mcCombinations.js
fill username/ fill password only functionality
> fill username/ fill password only functionality

- vendor/mooltipass/backend.js
Disable debug logging in Firefox.
See #125
> fixes #125

- _locales/de/messages.json
- _locales/en/messages.json
- _locales/es/messages.json
- _locales/fr/messages.json
- _locales/it/messages.json
- _locales/ja/messages.json
- _locales/ko/messages.json
- _locales/nl/messages.json
- _locales/pt_BR/messages.json
- _locales/ru/messages.json
- _locales/tr/messages.json
- _locales/zh_CN/messages.json
- _locales/zh_TW/messages.json
- options/options.html
> Password length 64

- MooltipassXCODEProject/MooltipassXCODEProject.xcodeproj/project.pbxproj
New identifiers  for Safari extension
> New identifiers

- ui/password-dialog/password-dialog.js
functionality for "Re generate" button for Safari
> functionality for "Re generate" button for Safari

- vendor/mooltipass/mcCombinations.js
meraki.com special combimation
> meraki.com special combimation

- manifest.json
- vendor/mooltipass/mcCombinations.js
functionality for microsoftonline.com and youtube in exclude_matches
> microsoftonline and youtube

- vendor/mooltipass/mcCombinations.js
> fix for https://navient.com/

- vendor/mooltipass/device.js
- vendor/mooltipass/mcCombinations.js
2 attempts for credentials, fix for mpiphp.org
> 2 attempts for credentials, fix for mpiphp.org

- vendor/mooltipass/mcCombinations.js
fix for doctorlib (additional item in IGNORE_PATTERNS)
> fix for doctorlib

- vendor/mooltipass/mcCombinations.js
New spec ial combinations for
ros.ie
auth0.openai.com
New item in  IGNORE_PATTERNS for
www.stib-mivb.be
> New spec ial combinations and IGNORE_PATTERNS

- content_scripts/mpDialog.js
- ui/password-dialog/password-dialog.js
Disable password generator when not connected to device
> Disable password generator when not connected to device

- vendor/mooltipass/device.js
- vendor/mooltipass/mcCombinations.js
fix for response processing when credentials request was denied
> fix for response processing when credentials request was denied

- vendor/mooltipass/mcCombinations.js
Special combination for docker.com
> Special combination for docker.com

- extension_mv2/content_scripts/mpDialog.js
- extension_mv2/vendor/mooltipass/mcCombinations.js
- extension_mv3/content_scripts/mpDialog.js
- extension_mv3/vendor/mooltipass/mcCombinations.js
> fix for sunrise.ch
